# Generated by Django 2.2 on 2020-06-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poivre', '0002_auto_20200623_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remise',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
