# Generated by Django 2.2 on 2020-06-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poivre', '0005_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poivre.Categorie'),
            preserve_default=False,
        ),
    ]
