# Generated by Django 2.2 on 2020-06-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poivre', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
